### ISSUE TITLE
Home content

### ISSUE THREAD

**Issue by carduz** [hypermedia2016/web#20]
![schermata del 2016-07-17 12-12-02](https://cloud.githubusercontent.com/assets/10631614/16900013/be95a6be-4c17-11e6-9b7b-694e588d9493.png)

**Comment by DeadManPoe** [comment]
Can u explain better? The "Test" is coming from the db

**Comment by carduz** [comment]
I mean we have only this image, you should give me other images

**Comment by DeadManPoe** [comment]
fixed
