### ISSUE TITLE
right proportions for images 

### ISSUE THREAD

**Issue by carduz** [hypermedia2016/web#21]
![schermata del 2016-07-17 12-13-16](https://cloud.githubusercontent.com/assets/10631614/16900020/df8f700c-4c17-11e6-951b-3b87c56e697e.png)

**Comment by DeadManPoe** [comment]
Fixed

**Comment by carduz** [comment]
we have this issue also in other sections like service

**Comment by DeadManPoe** [comment]
That should be fixed

**Comment by carduz** [comment]
I think so
