### ISSUE TITLE
FIX or

### ISSUE THREAD

**Issue by carduz** [hypermedia2016/web#27]
![schermata del 2016-07-17 17-50-26](https://cloud.githubusercontent.com/assets/10631614/16901529/f78d3f3e-4c46-11e6-8556-843ef0685e5e.png)

**Comment by carduz** [comment]
![schermata del 2016-07-17 17-51-17](https://cloud.githubusercontent.com/assets/10631614/16901535/12e301d8-4c47-11e6-97d0-b070456538de.png)

**Comment by carduz** [comment]
![schermata del 2016-07-17 17-51-39](https://cloud.githubusercontent.com/assets/10631614/16901538/2081a434-4c47-11e6-83e6-3cece564c99a.png)

**Comment by DeadManPoe** [comment]
to solve add "margin: 30px 0;" to the or div
