### ISSUE TITLE
Disable unused buttons (only 3 images case)

### ISSUE THREAD

**Issue by carduz** [hypermedia2016/web#43]
![schermata del 2016-07-18 11-56-10](https://cloud.githubusercontent.com/assets/10631614/16911430/abaf113a-4cde-11e6-8c00-bc091ff9f7e2.png)

**Comment by DeadManPoe** [comment]
Fixed

**Comment by carduz** [comment]
do this also in assistance

**Comment by DeadManPoe** [comment]
fixed

**Comment by carduz** [comment]
![schermata del 2016-07-18 19-14-56](https://cloud.githubusercontent.com/assets/10631614/16923727/ecf9495c-4d1b-11e6-9565-dd4959329bcb.png)
now we have this problem

**Comment by DeadManPoe** [comment]
fixed

**Comment by carduz** [comment]
when?

**Comment by DeadManPoe** [comment]
now

**Comment by DeadManPoe** [comment]
anzi un bel po di tempo fa
